# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/programming/roguelike

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/programming/roguelike

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/programming/roguelike/CMakeFiles /home/daniel/programming/roguelike/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/programming/roguelike/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named roguelike

# Build rule for target.
roguelike: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roguelike
.PHONY : roguelike

# fast build rule for target.
roguelike/fast:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/build
.PHONY : roguelike/fast

armour.o: armour.cpp.o
.PHONY : armour.o

# target to build an object file
armour.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/armour.cpp.o
.PHONY : armour.cpp.o

armour.i: armour.cpp.i
.PHONY : armour.i

# target to preprocess a source file
armour.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/armour.cpp.i
.PHONY : armour.cpp.i

armour.s: armour.cpp.s
.PHONY : armour.s

# target to generate assembly for a file
armour.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/armour.cpp.s
.PHONY : armour.cpp.s

buff.o: buff.cpp.o
.PHONY : buff.o

# target to build an object file
buff.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/buff.cpp.o
.PHONY : buff.cpp.o

buff.i: buff.cpp.i
.PHONY : buff.i

# target to preprocess a source file
buff.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/buff.cpp.i
.PHONY : buff.cpp.i

buff.s: buff.cpp.s
.PHONY : buff.s

# target to generate assembly for a file
buff.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/buff.cpp.s
.PHONY : buff.cpp.s

character.o: character.cpp.o
.PHONY : character.o

# target to build an object file
character.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/character.cpp.o
.PHONY : character.cpp.o

character.i: character.cpp.i
.PHONY : character.i

# target to preprocess a source file
character.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/character.cpp.i
.PHONY : character.cpp.i

character.s: character.cpp.s
.PHONY : character.s

# target to generate assembly for a file
character.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/character.cpp.s
.PHONY : character.cpp.s

display.o: display.cpp.o
.PHONY : display.o

# target to build an object file
display.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/display.cpp.o
.PHONY : display.cpp.o

display.i: display.cpp.i
.PHONY : display.i

# target to preprocess a source file
display.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/display.cpp.i
.PHONY : display.cpp.i

display.s: display.cpp.s
.PHONY : display.s

# target to generate assembly for a file
display.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/display.cpp.s
.PHONY : display.cpp.s

effect.o: effect.cpp.o
.PHONY : effect.o

# target to build an object file
effect.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/effect.cpp.o
.PHONY : effect.cpp.o

effect.i: effect.cpp.i
.PHONY : effect.i

# target to preprocess a source file
effect.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/effect.cpp.i
.PHONY : effect.cpp.i

effect.s: effect.cpp.s
.PHONY : effect.s

# target to generate assembly for a file
effect.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/effect.cpp.s
.PHONY : effect.cpp.s

floor.o: floor.cpp.o
.PHONY : floor.o

# target to build an object file
floor.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/floor.cpp.o
.PHONY : floor.cpp.o

floor.i: floor.cpp.i
.PHONY : floor.i

# target to preprocess a source file
floor.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/floor.cpp.i
.PHONY : floor.cpp.i

floor.s: floor.cpp.s
.PHONY : floor.s

# target to generate assembly for a file
floor.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/floor.cpp.s
.PHONY : floor.cpp.s

floortile.o: floortile.cpp.o
.PHONY : floortile.o

# target to build an object file
floortile.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/floortile.cpp.o
.PHONY : floortile.cpp.o

floortile.i: floortile.cpp.i
.PHONY : floortile.i

# target to preprocess a source file
floortile.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/floortile.cpp.i
.PHONY : floortile.cpp.i

floortile.s: floortile.cpp.s
.PHONY : floortile.s

# target to generate assembly for a file
floortile.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/floortile.cpp.s
.PHONY : floortile.cpp.s

hand.o: hand.cpp.o
.PHONY : hand.o

# target to build an object file
hand.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/hand.cpp.o
.PHONY : hand.cpp.o

hand.i: hand.cpp.i
.PHONY : hand.i

# target to preprocess a source file
hand.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/hand.cpp.i
.PHONY : hand.cpp.i

hand.s: hand.cpp.s
.PHONY : hand.s

# target to generate assembly for a file
hand.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/hand.cpp.s
.PHONY : hand.cpp.s

item.o: item.cpp.o
.PHONY : item.o

# target to build an object file
item.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/item.cpp.o
.PHONY : item.cpp.o

item.i: item.cpp.i
.PHONY : item.i

# target to preprocess a source file
item.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/item.cpp.i
.PHONY : item.cpp.i

item.s: item.cpp.s
.PHONY : item.s

# target to generate assembly for a file
item.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/item.cpp.s
.PHONY : item.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/main.cpp.s
.PHONY : main.cpp.s

race.o: race.cpp.o
.PHONY : race.o

# target to build an object file
race.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/race.cpp.o
.PHONY : race.cpp.o

race.i: race.cpp.i
.PHONY : race.i

# target to preprocess a source file
race.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/race.cpp.i
.PHONY : race.cpp.i

race.s: race.cpp.s
.PHONY : race.s

# target to generate assembly for a file
race.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/race.cpp.s
.PHONY : race.cpp.s

resistance.o: resistance.cpp.o
.PHONY : resistance.o

# target to build an object file
resistance.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/resistance.cpp.o
.PHONY : resistance.cpp.o

resistance.i: resistance.cpp.i
.PHONY : resistance.i

# target to preprocess a source file
resistance.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/resistance.cpp.i
.PHONY : resistance.cpp.i

resistance.s: resistance.cpp.s
.PHONY : resistance.s

# target to generate assembly for a file
resistance.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/resistance.cpp.s
.PHONY : resistance.cpp.s

shield.o: shield.cpp.o
.PHONY : shield.o

# target to build an object file
shield.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/shield.cpp.o
.PHONY : shield.cpp.o

shield.i: shield.cpp.i
.PHONY : shield.i

# target to preprocess a source file
shield.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/shield.cpp.i
.PHONY : shield.cpp.i

shield.s: shield.cpp.s
.PHONY : shield.s

# target to generate assembly for a file
shield.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/shield.cpp.s
.PHONY : shield.cpp.s

weapon.o: weapon.cpp.o
.PHONY : weapon.o

# target to build an object file
weapon.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/weapon.cpp.o
.PHONY : weapon.cpp.o

weapon.i: weapon.cpp.i
.PHONY : weapon.i

# target to preprocess a source file
weapon.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/weapon.cpp.i
.PHONY : weapon.cpp.i

weapon.s: weapon.cpp.s
.PHONY : weapon.s

# target to generate assembly for a file
weapon.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/weapon.cpp.s
.PHONY : weapon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... roguelike"
	@echo "... armour.o"
	@echo "... armour.i"
	@echo "... armour.s"
	@echo "... buff.o"
	@echo "... buff.i"
	@echo "... buff.s"
	@echo "... character.o"
	@echo "... character.i"
	@echo "... character.s"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... effect.o"
	@echo "... effect.i"
	@echo "... effect.s"
	@echo "... floor.o"
	@echo "... floor.i"
	@echo "... floor.s"
	@echo "... floortile.o"
	@echo "... floortile.i"
	@echo "... floortile.s"
	@echo "... hand.o"
	@echo "... hand.i"
	@echo "... hand.s"
	@echo "... item.o"
	@echo "... item.i"
	@echo "... item.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... race.o"
	@echo "... race.i"
	@echo "... race.s"
	@echo "... resistance.o"
	@echo "... resistance.i"
	@echo "... resistance.s"
	@echo "... shield.o"
	@echo "... shield.i"
	@echo "... shield.s"
	@echo "... weapon.o"
	@echo "... weapon.i"
	@echo "... weapon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

